version: '3'
services:
  web:
    build: ./web
    ports:
      - "8663:8663"
    links:
      - api
    volumes:
      - ./web/src:/app/src
  api:
    build: ./api
    ports:
      - "8662:8662"
    environment:
      - AQUEDUCT_API_KEY_ID
    links:
      - aqueduct-remote
    volumes:
      - ./api/data:/app/data
      - ./api/dist:/app/dist
  aqueduct-remote:
    build: ./aqueduct-remote
    ports:
      - "8700:8700"
    environment:
      - AQUEDUCT_API_KEY_ID
      - ETHEREUM_CHAIN
    links:
      - parity
    volumes:
      - ./aqueduct-remote/dist:/app/dist
  parity:
    build: ./parity
    ports:
      - "8180:8180"
      - "8546:8546"
      - "30303:30303"
      - "8545:8545"
    environment:
      - ETHEREUM_CHAIN
      - AQUEDUCT_API_KEY_ID
    volumes:
      - ./parity-data:/root/.local/share/io.parity.ethereum/
    entrypoint: /bin/bash
    command: ["/runtime-scripts/start.sh"]
